/*
* msg_proc.c: implementation of the
* remote procedure "printmessage"
*/

#include <stdio.h>
#include "msg.h" /* msg.h generated by rpcgen */

int * printmessage_1_svc(char **msg, struct svc_req *req)

{
   static int result; /* must be static! */
   fprintf(stdout, "%s\n", *msg);
   result = 1;
   return (&result);
}
